### ISSUE TITLE
Add this info on command line completion to  docs/readme

### ISSUE THREAD

**Issue by BlueDrink9** [hachy/cmdpalette.nvim#3]
You can get tab completion for vim commands in the window like this: ` vim.keymap.set('i', '<tab>', '<c-x><c-v>', {buffer=true})`

For details see `:h i_CTRL-X_CTRL-V`

Sadly this doesn't merge filetype completion like other commands.

This is how I map it. I set `filetype` to be `cmdpalette` in opts.
```lua
      local function bufmap()
        vim.keymap.set('i', '<tab>', '<c-x><c-v>', {buffer=true})
      end
      vim.api.nvim_create_autocmd("filetype", {
        pattern="cmdpalette",   callback=bufmap
      })
```

**Comment by hachy** [comment]
Thank you for the info. I have added it to the docs.
